baseURL: https://soggra.com
title: Soggra
paginate: 6
theme: charlolamode



menu:
    main:
        - name: About
          url: about/


params:
    author: Soggra
    description: Hi, I am Soggra, The biggest boss in the world (no cap).


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Soggra 👋
        description: Ula
        imageUrl: "/images/profile.png"
        imageTitle: Idan
        imageWidth: 200
        imageHeight: 200
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/@SoilWay_
    mainSections:
      - articles

    socialIcons:
        - name: youtube
          url: "https://www.youtube.com/@SoilWay_"
        - name: instagram
          url: "https://instagram.com/idan.mardehayev"


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

